# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/mongodb/rails/helloworld"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/mongodb/ruby"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/mysql/ruby"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/postgresql/ruby"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/redis/rails/helloworld"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/redis/sinatra"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/sqlserver/ruby"
    schedule:
      interval: "weekly"
